---@alias hlGroups 'Matchwith'|'MatchwithOut'|'MatchwithSign'
---@alias hlKeys 'ON'|'OFF'|'SIGN'
-- [1]:Start row, [2]:Start column, [3]:End column
---@alias WordRange {[1]:integer,[2]:integer,[3]:integer}
---@alias MatchItem {node:TSNode,range:Range4,is_start_point:boolean}
---@alias Last {word:WordRange,state:LastState,next_match:TSNode|vim.NIL}
-- Node ranges and their paired node ranges retrieved in the last session.
-- [1]:Markerd range, [2]:Paired range
---@alias LastState {[1]:Range4,[2]:Range4}
---@alias SearchPairs {chars:string[],matchpair:table<string,string[]>}
-- The starting line and ending line of the highlight are specified.
-- The ending line must be incremented by 1 to be included in the range.
---@alias Marker integer[]
---@alias IsStartPoint boolean

---@class Options
---@field public captures string[]
---@field public debounce_time? integer
---@field public ignore_buftypes? string[]
---@field public ignore_filetypes? string[]
---@field public indicator? integer
---@field public jump_key? string
---@field public sign? boolean
---@field public symbols table<string,string>

---@class Cache
---@field private ns integer
---@field private hlgroups {[hlKeys]:hlGroups}
---@field private hldetails {[hlGroups]: vim.api.keyset.highlight}
---@field private searchpairs SearchPairs
---@field private changetick integer
---@field private last Last
---@field private marker Marker
---@field private skip_matching boolean

---@class Instance
---@field public mode string
---@field public is_insert_mode boolean
---@field public bufnr integer
---@field public winid integer
---@field public filetype string
---@field public changetick integer
---@field public top_row integer
---@field public bottom_row integer
---@field public cur_row integer
---@field public cur_col integer
---@field public sentence string
---@field public opt Options
---@field public match MatchItem
---@field public next_match TSNode|vim.NIL
---@field public node_ranges Range4[]
---@field public marker Marker
---@field public last Last

---@class Matchwith: Instance
---@field public opt Options
---@field clear_ns fun(self:self):boolean
---@field new fun(is_insert_mode:boolean,row?:integer,col?:integer):Matchwith
---@field get_matches fun(self:self)
---@field get_pair_pos fun(self:self,searchpair_opts:string[]):integer[]
---@field verify_searchpairpos fun(self:self):boolean
---@field get_matchpair fun(self:self)
---@field pair_marker_state fun(self:self,pair_range:WordRange):integer
---@field set_searchpairs fun():nil
---@field draw_markers fun(self:self)
---@field add_marker fun(self:self,group:hlGroups,word_range:WordRange)
---@field set_indicator fun(self:self,symbol:string|nil)
---@field matching fun(is_insert_mode?:boolean,row?:integer,col?:integer):boolean?
---@field jumping fun(self:self)
---@field setup fun(opts:Options,force:boolean)

---@class TODO
---@field set_matchpairs fun(self:self)
---@field matchpairs table<integer,string[]>
