---@alias Hlgroups 'Matchwith'|'MatchwithOut'|'MatchwithSign'|'MatchwithParent'|'MatchwithParentOut'
---@alias HlKeys 'ON'|'OFF'|'SIGN'|'PARENT_ON'|'PARENT_OFF'
-- [1]:Start row, [2]:Start column, [3]:End column
---@alias WordRange {[1]:integer,[2]:integer,[3]:integer}
---@alias MatchItem {node:TSNode,range:Range4,at_cursor:boolean,is_comment:boolean,is_start_point:IsStartPoint}
---@alias Last {word:WordRange,current:LastState,parent:LastState}
-- Node ranges and their paired node ranges retrieved in the last session.
-- [1]:Markerd range, [2]:Paired range
---@alias LastState {[1]:Range4,[2]:Range4}
---@alias SearchPairs {chars:string[],matchpair:table<string,string[]>}
-- The starting line and ending line of the highlight are specified.
-- The ending line must be incremented by 1 to be included in the range.
---@alias Markers {current?:Range2,parent?:Range2}
---@alias IsStartPoint boolean

---@class Options
---@field public debounce_time? integer
---@field public depth_limit? integer
---@field public ignore_filetypes string[]
---@field public ignore_buftypes? string[]
---@field public captures string[]
---@field public jump_key? string
---@field public indicator? integer
---@field public sign? boolean
---@field public show_parent? boolean
---@field public show_next? boolean
---@field public symbols table<string,string>

---@class Cache
---@field private ns integer
---@field private hlgroup {[HlKeys]:Hlgroups}
---@field private hldetails {[Hlgroups]: vim.api.keyset.highlight}
---@field private searchpairs SearchPairs
---@field private changetick integer
---@field private last Last
---@field private markers Markers
---@field private skip_matching boolean

---@class Instance
---@field public mode string
---@field public bufnr integer
---@field public winid integer
---@field public filetype string
---@field public changetick integer
---@field public top_row integer
---@field public bottom_row integer
---@field public cur_row integer
---@field public cur_col integer
---@field public sentence string
---@field public opt Options
---@field public match MatchItem
---@field public next_match TSNode
---@field public node_ranges Range4[]
---@field public markers Markers
---@field public last Last

---@class Matchwith: Instance
---@field public opt Options
---@field util_call fun():util
---@field clear_ns fun(self:self,marker:Range2):boolean
---@field new fun(row?:integer,col?:integer):Matchwith
---@field get_matches fun(self:self)
---@field verify_searchpairpos fun(self:self)
---@field verify_next_match fun(self:self)
---@field get_matchpair fun(self:self)
---@field pair_marker_state fun(self:self,pair:WordRange):integer
---@field set_matchpairs_list fun():nil
---@field draw_markers fun(self:self)
---@field add_marker fun(self:self,group:Hlgroups,word_range:WordRange)
---@field set_indicator fun(self:self,symbol:string|nil)
---@field matching fun(row?:integer,col?:integer):boolean?
---@field jumping fun(self:self)
---@field setup fun(opts:Options,force:boolean)

---@class TODO
---@field set_matchpairs fun(self:self)
---@field matchpairs table<integer,string[]>
